#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xset s off
xset -dpms
xset s noblank

killall -q polybar
sleep 1 &
polybar &

nitrogen --restore &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config top_padding          22
bspc config bottom_padding        0
bspc config border_width          6
bspc config window_gap           16
bspc config focused_border_color "#c3afaf"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Nitrogen state=floating rectangle=800x600+0+0 center=true
bspc rule -a mpv state=floating rectangle=960x540+0+0 center=true
bspc rule -a Viewnior state=floating rectangle=960x540+0+0 center=true
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
