#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# Scripts directory
HERB=~/.config/herbstluftwm
SCRIPTS=$HERB/scripts

#Set wallpaper/background
feh --bg-scale /home/zed/Bilder/wallpapers/blade/blade-city.jpg
#xsetroot -solid '#444444'

# disable screensaver
xset s off
xset s noblank
xset -dpms

# autostart daemons'n'stuff
#zzzfm -d &
#devmon &
#leafpad $HERB/help.txt &
xrdb merge ~/.Xresources

###################################################################################################
hc set default_frame_layout horizontal
hc substitute ALGO settings.default_frame_layout \
   foreach T tags.by-name. \
   sprintf ATTR '%c.tiling.root.algorithm' T \
   set_attr ATTR ALGO

###################################################################################################

# remove all existing keybindings
hc keyunbind --all

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
#Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier

hc keybind $Mod-Shift-e quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
#hc keybind $Mod-Shift-b spawn sudo persist-config --shutdown --command reboot
hc keybind $Mod-Shift-b spawn systemctl reboot
hc keybind $Mod-Shift-q spawn systemctl poweroff

# Media volume
hc keybind Control-Up spawn ~/.config/herbstluftwm/scripts/volume.sh up
hc keybind Control-Down spawn  ~/.config/herbstluftwm/scripts/volume.sh down

# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
#hc keybind $Mod-h     focus left
#hc keybind $Mod-j     focus down
#hc keybind $Mod-k     focus up
#hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
#hc keybind $Mod-Shift-h     shift left
#hc keybind $Mod-Shift-j     shift down
#hc keybind $Mod-Shift-k     shift up
#hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-v       split   bottom  0.5
hc keybind $Mod-h       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
# resizestep_h=${resizestep_h:-0.005}
 #resizestep_v=${resizestep_v:-0.02}
#hc keybind $Mod-Control-h       resize left +$resizestep
#hc keybind $Mod-Control-j       resize down +$resizestep
#hc keybind $Mod-Control-k       resize up +$resizestep
#hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Alt-Left    resize left +$resizestep
hc keybind $Mod-Alt-Down    resize down +$resizestep
hc keybind $Mod-Alt-Up      resize up +$resizestep
hc keybind $Mod-Alt-Right   resize right +$resizestep

# +$resizestep

# Open apps
hc keybind $Mod-Return spawn lxterminal
hc keybind $Mod-d spawn dmenu_run -fn LiberationSans-12
hc keybind $Mod-f spawn pcmanfm
hc keybind $Mod-e spawn mousepad
hc keybind $Mod-w spawn google-chrome
#hc keybind $Mod-n spawn firefox-esr
#hc keybind $Mod-y spawn seamonkey

# screenshots
hc keybind $Mod-F12 spawn scrot -t 20 -d 2 ~/%Y-%m-%d-%T-screenshot.png

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-Control-Right use_index +1 --skip-visible
hc keybind $Mod-Control-Left  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-m fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_gap 8
hc set frame_padding -12
hc set frame_border_width 2
hc set frame_transparent_width 0
hc set window_gap 12
hc set window_border_width 2
hc set window_border_inner_width 0

# frame options
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 0
hc set mouse_recenter_gap 0

# colors
hc set frame_border_active_color  '#ff005f'
hc set frame_border_normal_color  '#262626'
hc set frame_bg_active_color      '#ff005f'
hc set frame_bg_normal_color      '#262626'
hc set window_border_active_color '#ff005f'
hc set window_border_normal_color '#262626'
done
hc attr theme.tiling.outer_width 1
hc attr theme.background_color '#141414'

hc set window_gap 10
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule class=Gtkdialog floating=on
hc rule class=Wallpaper floating=on
hc rule class="Desktop-session-exit.py" floating=on


hc set tree_style '╾│ ├└╼─┐'

# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" "$monitor" &
done
